/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameTheory;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rasito7659
 */
public class gtForm extends javax.swing.JFrame {

    /**
     * Creates new form gtForm
     */
    public gtForm() {
        initComponents();
        this.setLocationRelativeTo(null); //membuat tampilan tetap ditengah
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizedBUtton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        s11 = new javax.swing.JTextField();
        s12 = new javax.swing.JTextField();
        s13 = new javax.swing.JTextField();
        s21 = new javax.swing.JTextField();
        s22 = new javax.swing.JTextField();
        s23 = new javax.swing.JTextField();
        s31 = new javax.swing.JTextField();
        s32 = new javax.swing.JTextField();
        s33 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mins1Cell = new javax.swing.JTextField();
        mins2Cell = new javax.swing.JTextField();
        mins3Cell = new javax.swing.JTextField();
        maxs1Cell = new javax.swing.JTextField();
        maxs2Cell = new javax.swing.JTextField();
        maxs3Cell = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        maksiminCell = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        minimaxCell = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spACell = new javax.swing.JTextField();
        spBCell = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        strCell = new javax.swing.JTextField();
        rsCell = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultCell = new javax.swing.JTextArea();
        prosesButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        minimizedBUtton.setBackground(new java.awt.Color(252, 185, 65));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 49, 63));
        jLabel1.setText("-");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(34, 49, 63));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout minimizedBUttonLayout = new javax.swing.GroupLayout(minimizedBUtton);
        minimizedBUtton.setLayout(minimizedBUttonLayout);
        minimizedBUttonLayout.setHorizontalGroup(
            minimizedBUttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimizedBUttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        minimizedBUttonLayout.setVerticalGroup(
            minimizedBUttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizedBUttonLayout.createSequentialGroup()
                .addGroup(minimizedBUttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 110, 123));

        jPanel1.setBackground(new java.awt.Color(250, 190, 88));

        s11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s11.setForeground(new java.awt.Color(34, 49, 63));

        s12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s12.setForeground(new java.awt.Color(34, 49, 63));
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });

        s13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s13.setForeground(new java.awt.Color(34, 49, 63));

        s21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s21.setForeground(new java.awt.Color(34, 49, 63));

        s22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s22.setForeground(new java.awt.Color(34, 49, 63));

        s23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s23.setForeground(new java.awt.Color(34, 49, 63));

        s31.setForeground(new java.awt.Color(34, 49, 63));

        s32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s32.setForeground(new java.awt.Color(34, 49, 63));

        s33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        s33.setForeground(new java.awt.Color(34, 49, 63));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 49, 63));
        jLabel3.setText("Object B");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 49, 63));
        jLabel4.setText("Object A");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 49, 63));
        jLabel2.setText("S1");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 49, 63));
        jLabel5.setText("S2");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 49, 63));
        jLabel6.setText("S3");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 49, 63));
        jLabel7.setText("s1");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 49, 63));
        jLabel8.setText("s2");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 49, 63));
        jLabel9.setText("s3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(s31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s33)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(s13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(s23))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(253, 227, 167));
        jLabel10.setText("MINIMAL");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(253, 227, 167));
        jLabel11.setText("MAKSIMAL");

        mins1Cell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mins1Cell.setForeground(new java.awt.Color(16, 51, 142));
        mins1Cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mins2Cell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mins2Cell.setForeground(new java.awt.Color(16, 51, 142));
        mins2Cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mins3Cell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mins3Cell.setForeground(new java.awt.Color(16, 51, 142));
        mins3Cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        maxs1Cell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maxs1Cell.setForeground(new java.awt.Color(16, 51, 142));
        maxs1Cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxs1Cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxs1CellActionPerformed(evt);
            }
        });

        maxs2Cell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maxs2Cell.setForeground(new java.awt.Color(16, 51, 142));
        maxs2Cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxs2Cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxs2CellActionPerformed(evt);
            }
        });

        maxs3Cell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maxs3Cell.setForeground(new java.awt.Color(16, 51, 142));
        maxs3Cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxs3Cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxs3CellActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(253, 227, 167));
        jLabel12.setText("MAKSIMIN");

        maksiminCell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        maksiminCell.setForeground(new java.awt.Color(252, 185, 65));
        maksiminCell.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(253, 227, 167));
        jLabel13.setText("MINIMAKS");

        minimaxCell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        minimaxCell.setForeground(new java.awt.Color(252, 185, 65));
        minimaxCell.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(253, 227, 167));
        jLabel14.setText("Saddle Poin A");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(253, 227, 167));
        jLabel15.setText("Saddle Point B");

        spACell.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        spACell.setForeground(new java.awt.Color(35, 100, 66));
        spACell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spACell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spACellActionPerformed(evt);
            }
        });

        spBCell.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        spBCell.setForeground(new java.awt.Color(218, 171, 45));
        spBCell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spBCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spBCellActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(253, 227, 167));
        jLabel16.setText("Strategi");

        strCell.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        strCell.setForeground(new java.awt.Color(34, 49, 63));

        rsCell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rsCell.setForeground(new java.awt.Color(253, 227, 167));
        rsCell.setText("Hasil");

        resultCell.setColumns(20);
        resultCell.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        resultCell.setForeground(new java.awt.Color(34, 49, 63));
        resultCell.setRows(5);
        jScrollPane1.setViewportView(resultCell);

        prosesButton.setBackground(new java.awt.Color(123, 239, 178));
        prosesButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        prosesButton.setForeground(new java.awt.Color(34, 49, 63));
        prosesButton.setText("Proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(254, 241, 96));
        resetButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resetButton.setForeground(new java.awt.Color(34, 49, 63));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mins1Cell)
                            .addComponent(mins2Cell)
                            .addComponent(mins3Cell)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxs1Cell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxs2Cell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxs3Cell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prosesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maksiminCell, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minimaxCell, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spACell, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spBCell, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addComponent(jLabel16)
                    .addComponent(rsCell)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(strCell, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spACell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spBCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(strCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rsCell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mins1Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mins2Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mins3Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(maxs1Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxs2Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxs3Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(maksiminCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(minimaxCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(prosesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizedBUtton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(minimizedBUtton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        this.setState(JFrame.ICONIFIED); //menjadikan program minimized
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked

        //memanggil class indexForm
        indexForm iF = new indexForm();
        iF.setVisible(true);    //menampilkan menu index
        setVisible(false);      //menyembunyikan menu saat ini

    }//GEN-LAST:event_backButtonMouseClicked

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s12ActionPerformed

    private void maxs1CellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxs1CellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxs1CellActionPerformed

    private void maxs2CellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxs2CellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxs2CellActionPerformed

    private void maxs3CellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxs3CellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxs3CellActionPerformed

    private void spACellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spACellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spACellActionPerformed

    private void spBCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spBCellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spBCellActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        
        //inisiasi array untuk data inputan
        float [][] data;
        data = new float[3][3];
        
        //mengambil nilai inputan dan menyimpan ke array
        data[0][0] = Float.parseFloat(this.s11.getText());
        data[0][1] = Float.parseFloat(this.s12.getText());
        data[0][2] = Float.parseFloat(this.s13.getText());
        data[1][0] = Float.parseFloat(this.s21.getText());
        data[1][1] = Float.parseFloat(this.s22.getText());
        data[1][2] = Float.parseFloat(this.s23.getText());
        data[2][0] = Float.parseFloat(this.s31.getText());
        data[2][1] = Float.parseFloat(this.s32.getText());
        data[2][2] = Float.parseFloat(this.s33.getText());
        
        //memanggil class pureSTR
        pureSTR pstr = new pureSTR(data);
        
        pstr.count_min();       //menjalankan method count_min() pada pureSTR
        String min1 = Float.toString(pstr.mini[0]); //menjadikan nilai float ke string
        mins1Cell.setText(min1);    //menampilkan nilai string pada menu
        String min2 = Float.toString(pstr.mini[1]);
        mins2Cell.setText(min2);
        String min3 = Float.toString(pstr.mini[2]);
        mins3Cell.setText(min3);
        
        pstr.count_max();       //menjalankan method count_max() pada pureSTR
        String max1 = Float.toString(pstr.maxi[0]);
        maxs1Cell.setText(max1);
        String max2 = Float.toString(pstr.maxi[1]);
        maxs2Cell.setText(max2);
        String max3 = Float.toString(pstr.maxi[2]);
        maxs3Cell.setText(max3);
        
        pstr.find_maximin();    //menjalankan method find_maximin() untuk mecari nilai maksimin
        String maximin = Float.toString(pstr.maksimin);
        maksiminCell.setText(maximin);
        pstr.find_minimax();    //menjalankan method find_minimax() untuk mencari nilai minimaks
        String minimax = Float.toString(pstr.minimax);
        minimaxCell.setText(minimax);
        
        if(pstr.spa == pstr.spb){ //pengecekan nilai saddle point
            
            String psa = Float.toString(pstr.spa);
            spACell.setText(psa);
            String psb = Float.toString(pstr.spb);
            spBCell.setText(psb);
            
            strCell.setText("Strategi Murni"); //karena saddle point sama ditampilkan murni
            
            JOptionPane.showMessageDialog(null,"Proses Selesai");
            resultCell.setText("Hasil : "+psa+" "
                    + "\nPemain A dengan strategi "+pstr.sa+""      //print hasil
                            + "\nPemain B dengan strategi "+pstr.sb);
                    
        }else{
            //karena saddle point tidak sama masuk ke metode campuran
            
            //memanggil class mixSTR
            mixSTR mstr = new mixSTR(data,pstr.mini,pstr.maxi);
            mstr.spObjectA();   //menjalankan method untuk mencari nilai saddle point object A
            mstr.spObjectB();   //menjalankan method untuk mencari nilai saddle point object B
            
            if(mstr.spa==mstr.spb){ //pengecekan saddle point baru
                
                String psa = Float.toString(mstr.spa);
                spACell.setText(psa);
                String psb = Float.toString(mstr.spb);
                spBCell.setText(psb);

                strCell.setText("Strategi Campuran");

                JOptionPane.showMessageDialog(null, "Proses Selesai"
                        + "\nObject A:"
                        + "\nStrategi "+ (mstr.cursorx[0]+1) +": "+mstr.p+""    //peluang strategi object A
                        + "\nStrategi "+ (mstr.cursorx[1]+1) +": "+ (1-mstr.p) +""  //peluang strategi object A
                        + "\nObject B:"
                        + "\nStrategi "+ (mstr.cursory[0]+1) +": "+mstr.q+""    //peluang strategi object B
                        + "\nStrategi "+ (mstr.cursory[1]+1) +": "+ (1-mstr.q));    //peluang strategi object B
                resultCell.setText("Hasil:"
                        + "\nKeuntungan A dinaikkan dari "+pstr.maksimin+" menjadi "+mstr.spa+""
                        + "\nKerugian B diturunkan dari "+pstr.minimax+" menjadi "+mstr.spb);

            }
            
        }
        
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        
        //mereset inputan
        s11.setText("");
        s12.setText("");
        s13.setText("");
        s21.setText("");
        s22.setText("");
        s23.setText("");
        s31.setText("");
        s32.setText("");
        s33.setText("");
        
        //mereset minimal
        mins1Cell.setText("");
        mins2Cell.setText("");
        mins3Cell.setText("");
        
        //mereset maksimal
        maxs1Cell.setText("");
        maxs2Cell.setText("");
        maxs3Cell.setText("");
        
        maksiminCell.setText("");   //mereset maksimin
        minimaxCell.setText("");    //mereset minimaks
        
        spACell.setText("");        //mereset saddle point a
        spBCell.setText("");        //mereset saddle point b
        
        strCell.setText("");        //mereset strategi
        
        resultCell.setText("");     //mereset hasil
        
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gtForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gtForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maksiminCell;
    private javax.swing.JTextField maxs1Cell;
    private javax.swing.JTextField maxs2Cell;
    private javax.swing.JTextField maxs3Cell;
    private javax.swing.JTextField minimaxCell;
    private javax.swing.JPanel minimizedBUtton;
    private javax.swing.JTextField mins1Cell;
    private javax.swing.JTextField mins2Cell;
    private javax.swing.JTextField mins3Cell;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextArea resultCell;
    private javax.swing.JLabel rsCell;
    private javax.swing.JTextField s11;
    private javax.swing.JTextField s12;
    private javax.swing.JTextField s13;
    private javax.swing.JTextField s21;
    private javax.swing.JTextField s22;
    private javax.swing.JTextField s23;
    private javax.swing.JTextField s31;
    private javax.swing.JTextField s32;
    private javax.swing.JTextField s33;
    private javax.swing.JTextField spACell;
    private javax.swing.JTextField spBCell;
    private javax.swing.JTextField strCell;
    // End of variables declaration//GEN-END:variables
}
